----Aqui iniciamos con una arquitectura de microservicios
---realizar una arquitectua de ms para una tienda-bodega
CREATE TABLE TIENDAS_BODEGA(
ID_TIENDA NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(100)NOT NULL,
FECHA_APERTURA DATE
);
INSERT INTO TIENDAS_BODEGA VALUES(1,'SUCURSAL BODEGA AV.JUAREZ','29/05/2025');
COMMIT;

--ms-tienda---ESTE SERA MICROSERVICIOS PADRE O GENERAL---ORACLE

---MS HIJO--MS INVENTARIO--PRODUCTOS--H2(ESUNA BASE DE DATOS DE MEMORIA)---SIRVE PARA PROYECTOS DE PRUEBA

/*CREATE TABLE PRODUCTOS_BODEGA(
ID_PRODUCTO NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(90)NOT NULL,
PRECIO NUMBER NOT NULL,         ---ESTA NO SE CREO AQUI SE CREO EN H2 
STOCK INT NOT NULL,
ID_TIENDA NUMBER NOT NULL----LLAVE REFERENCIADA
)*/


--MS -HIJO---MS---VENTAS--CLIENTES--ORACLE
CREATE TABLE CLIENTES_BODEGA(
ID_PRODUCTO NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(90)NOT NULL,
APP VARCHAR(90)NOT NULL,
APM VARCHAR2(90),
NUM_CEL NUMBER NOT NULL,
ID_TIENDA NUMBER NOT NULL----LLAVE REFERENCIADA
);

INSERT INTO CLIENTES_BODEGA VALUES(1,'JOSE','PEREZ','LEON',23455657,1);
COMMIT;

---MS-APIGATEWAY(UNA UNICA PUERTA DE ENTRA PARA NUESTROS MS
